name: build
on:
  workflow_dispatch: 
  # push:
  #   branches:
  #   - master
  #   paths-ignore:
  #   - '.github/workflows/crud.yaml'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: "Checkout source code"
      uses: actions/checkout@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: "Build and push docker image"
      uses: docker/build-push-action@v2
      with:
        tags: possedan/example-app:${{ github.sha }}
        push: true
    - name: Deploy
      uses: cloudposse/actions/github/repository-dispatch@0.22.0
      if: github.ref == 'refs/heads/master'
      with:
        event-type: deploy
        client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}", "stage": ""}'
