name: deploy
on:
  repository_dispatch:
    types: [deploy]
jobs:
  deploy:
    runs-on: ubuntu-latest
    container:
      image: possedan/example-app:${{ github.event.client_payload.sha }}
    steps:
    - name: "Slack: Notify of Start"
      uses: 8398a7/action-slack@v3
      with:
        username: "CI/CD"
        icon_url: "https://avatars2.githubusercontent.com/in/15368"
        status: success
        fields: repo,message,commit,author,ref,workflow
        text: Deploying possedan/example-app:${{ github.event.client_payload.sha }} to ${{ github.event.client_payload.stage }}
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
    - name: "Checkout source code"
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.client_payload.ref }}
    - name: "Prep kubeconfig"
      run: |
        mkdir ~/.kube
        echo -n ${{ secrets.KUBECONFIG }} | base64 -d > ~/.kube/config
    - name: "Deploy with helmfile"
      env:
        RELEASE_NAME: example-app
        NAMESPACE: ${{ github.event.client_payload.stage }}
        IMAGE_NAME: possedan/example-app
        IMAGE_TAG: ${{ github.event.client_payload.sha }}
        APP_SCHEME: http
        APP_HOST: master.example.cloudposse.org
        COLOR: blue
      run: |
        echo 'Preparing to deploy possedan/example-app:${IMAGE_TAG}'
        apk add --update curl make bash git kubectl@cloudposse helm@cloudposse=3.1.3-r0 helmfile@cloudposse
        cd deploy
        helmfile --namespace ${NAMESPACE} --selector preview=true sync
  # github-status-update:
  #   runs-on: ubuntu-latest
  #   container:
  #     image: cloudposse/github-status-updater
  #   steps:
  #   - name: "Update Github Deployment Status"
  #     env:
  #       GITHUB_ACTION: update_state
  #       GITHUB_OWNER: ${{CF_REPO_OWNER}}
  #       GITHUB_REPO: ${{CF_REPO_NAME}}
  #       GITHUB_REF: ${{CF_REVISION}}
  #       GITHUB_CONTEXT: ${{STAGE}}/env
  #       GITHUB_STATE: success
  #       GITHUB_DESCRIPTION: Deployed to ${{NAMESPACE}} by @${{CF_BUILD_INITIATOR}}
  #       GITHUB_TARGET_URL: ${{APP_SCHEME}}://${{APP_HOST}}/dashboard
    - name: "Slack: Notify of Deployment Failure"
      uses: 8398a7/action-slack@v3
      if: failure()
      with:
        username: "CI/CD"
        icon_url: "https://avatars2.githubusercontent.com/in/15368"
        status: Failure
        fields: repo,message,commit,author,ref,workflow
        text: "Deployment Failed!"
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
    - name: "Slack: Notify of Finish"
      uses: 8398a7/action-slack@v3
      if: success()
      with:
        username: "CI/CD"
        icon_url: "https://avatars2.githubusercontent.com/in/15368"
        status: Success
        fields: repo,message,commit,author,ref,workflow
        text: "Deployment Succeeded!"
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
