name: destroy
on:
  workflow_dispatch: 
jobs:
  destroy:
    runs-on: ubuntu-latest
    container:
      image: possedan/example-app:${{ github.sha }}
    steps:
    - name: "Checkout source code"
      uses: actions/checkout@v2
    - name: "Prep kubeconfig"
      run: |
        mkdir ~/.kube
        echo -n ${{ secrets.KUBECONFIG }} | base64 -d > ~/.kube/config
    - name: "destroy with helmfile"
      env:
        RELEASE_NAME: example-app
        NAMESPACE: master
        COLOR: blue
      run: |
        echo 'Preparing to destroy possedan/example-app:${{ github.sha }}'
        apk add --update curl make bash git kubectl@cloudposse helm@cloudposse=3.1.3-r0 helmfile@cloudposse
        cd deploy
        helmfile --namespace master --selector preview=true destroy
