name: release
on:
  workflow_dispatch: 
  # push:
  #   branches:
  #   - master
  #   paths-ignore:
  #   - '.github/workflows/crud.yaml'
jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
    - name: "Checkout source code"
      uses: actions/checkout@v2
    - name: Set up Docker buildx
      uses: docker/setup-buildwx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    # Pull Image with commit SHA
    # Push Image with release tag

    # Ask for confirmation to release to staging
    # Release to Staging when approved
    
    # Ask for confirmation to release to production
    # Release to Production when approved

    # Example slack notifications
    # - name: Notify slack success
    #   if: success()
    #   env:
    #     SLACK_BOT_TOKEN: ${{ secrets.SLACK_TOKEN }}
    #   uses: voxmedia/github-action-slack-notify-build@v1
    #   with:
    #     channel: _some_channel
    #     status: SUCCESS
    #     color: good
    # - name: Notify slack fail
    #   if: failure()
    #   env:
    #     SLACK_BOT_TOKEN: ${{ secrets.SLACK_TOKEN }}
    #   uses: voxmedia/github-action-slack-notify-build@v1
    #   with:
    #     channel: _some_channel
    #     status: FAILED
    #     color: danger