name: notify-slack
on:
  workflow_run:
    workflows:
    - build
    - deploy
    - destroy
    - preview
    - release
    types:
    - completed
jobs:
  notify-slack:
    runs-on: ubuntu-latest
    container:
      image: cloudposse/github-status-updater
    steps:
    # Example slack notifications
    - name: Notify slack
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_TOKEN }}
      uses: voxmedia/github-action-slack-notify-build@v1
      with:
        channel: _some_channel
        status: SUCCESS  # Calculate this?
        color: good # Calculate this?
